#!/usr/bin/env bash
## SCRIPT TO RUN COMPLETE SCRuB ANALYSIS

echo "Start Date/Time: $(date)"

mkdir ../results/data
mkdir ../results/data/Fig_3
mkdir ../results/data/Fig_3/decontaminated-samples
mkdir ../results/Plots
mkdir ../results/Plots/fig_3
mkdir ../results/Supplementary_figures
mkdir ../results/Supplementary_figures/F_S10


echo "Date/Time: $(date)"

# echo "Running Run_plasma_deconts_and_preds.R..."
# Rscript Plasma/Run_plasma_deconts_and_preds.R



# drafting my own version with more broken out pieces...

echo -e "\n=========================================================\n"
echo "Date/Time: $(date)"
echo -e "before-decontamination.R ... \n"
Rscript ivory/before-decontamination.R 

echo -e "\n=========================================================\n"
echo "Date/Time: $(date)"
echo -e "decontaminate_not.R ... \n"
Rscript ivory/decontaminate_not.R

echo -e "\n=========================================================\n"
if [  1 -eq 0 ] 
then   
	echo "Date/Time: $(date)"
	echo -e "decontaminate_SCRuB.R ... \n"
	Rscript ivory/decontaminate_SCRuB.R 2
else
	echo "Skipping decontaminate_SCRuB.R."
fi

echo -e "\n=========================================================\n"
echo "Date/Time: $(date)"
echo -e "decontaminate_noPlate-SCRuB.R ... \n"
Rscript ivory/decontaminate_noPlate-SCRuB.R trials=2 dropBlanks=0

echo -e "\n=========================================================\n"
echo "Date/Time: $(date)"
echo -e "decontaminate_noPlate-SCRuB.R ... \n"
Rscript ivory/decontaminate_noPlate-SCRuB.R trials=2 dropBlanks=.3

echo -e "\n=========================================================\n"
echo "Date/Time: $(date)"
echo -e "decontaminate_noPlate-SCRuB.R ... \n"
Rscript ivory/decontaminate_noPlate-SCRuB.R trials=2 dropBlanks=.6

echo -e "\n=========================================================\n"
echo "Date/Time: $(date)"
echo -e "post-decont-vsnm-and-diversity.R ... \n"
Rscript ivory/post-decont-vsnm-and-diversity.R

echo -e "\n=========================================================\n"
echo "Date/Time: $(date)"
echo -e "alt-ML.R ... \n"
Rscript ivory/alt-ML.R



echo "End Date/Time: $(date)"
