#!/usr/bin/env bash
## SCRIPT TO RUN COMPLETE SCRuB ANALYSIS

echo "Start Date/Time: $(date)"

mkdir ../results/data
mkdir ../results/data/Fig_3
mkdir ../results/data/Fig_3/decontaminated-samples
mkdir ../results/Plots
mkdir ../results/Plots/fig_3
mkdir ../results/Supplementary_figures
mkdir ../results/Supplementary_figures/F_S10


echo "Date/Time: $(date)"

# echo "Running Run_plasma_deconts_and_preds.R..."
# Rscript Plasma/Run_plasma_deconts_and_preds.R



# drafting my own version with more broken out pieces...

echo -e "\n=========================================================\n"
echo -e "before-decontamination.R ... \n"
Rscript ivory/before-decontamination.R 

echo -e "\n=========================================================\n"
echo -e "decontaminate_SCRuB.R ... \n"
Rscript ivory/decontaminate_SCRuB.R 







echo "End Date/Time: $(date)"